CREATE TABLE IF NOT EXISTS Livre(
	ID             INTEGER PRIMARY KEY AUTOINCREMENT,
	IMG            TEXT ,
	TITRE          TEXT NOT NULL ,
	DESCRIPTION    TEXT ,
	NB_EX          INTEGER NOT NULL,
-- 	CONSTRAINT Livre_PK PRIMARY KEY (ID)
);


CREATE TABLE IF NOT EXISTS Auteurs(
	ID        INTEGER PRIMARY KEY AUTOINCREMENT,
	NOM       TEXT NOT NULL ,
	PRENOM    TEXT NOT NULL ,
-- 	CONSTRAINT Auteurs_PK PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS Etat(
	ID         INTEGER NOT NULL ,
	NOM_ETAT    TEXT NOT NULL,
	CONSTRAINT Etat_PK PRIMARY KEY (ID)
);



CREATE TABLE IF NOT EXISTS Exemplaires(
	ID                   INTEGER PRIMARY KEY AUTOINCREMENT,
	IMG                  TEXT,
	AN_EMIS             INTEGER NOT NULL ,
	NB_PAGES              INTEGER NOT NULL ,
	LANGUAE              TEXT NOT NULL ,
	PRIX                 REAL NOT NULL ,
	EMPLACE              INTEGER NOT NULL ,
	MAISONS_EDITION       TEXT NOT NULL,
	ID_LIVRE             TEXT NOT NULL ,
	ID__ETAT             TEXT NOT NULL
-- 	CONSTRAINT Exemplaires_PK PRIMARY KEY (ID)

	,CONSTRAINT Exemplaires_Livre_FK FOREIGN KEY (ID_LIVRE) REFERENCES Livre(ID)
	,CONSTRAINT Exemplaires_Etat0_FK FOREIGN KEY (ID__ETAT) REFERENCES Etat(ID)
);


CREATE TABLE IF NOT EXISTS Genre(
	ID       INTEGER PRIMARY KEY AUTOINCREMENT,
	TITRE    TEXT NOT NULL,
-- 	CONSTRAINT Genre_PK PRIMARY KEY (ID)
);


CREATE TABLE IF NOT EXISTS Role(
	ID             INTEGER NOT NULL ,
	DESIGNATION    TEXT NOT NULL,
	CONSTRAINT Role_PK PRIMARY KEY (ID)
);


CREATE TABLE IF NOT EXISTS Utilisateur(
	PASSPORT_ID TEXT PRIMARY KEY,
-- 	NICKNAME    TEXT NOT NULL ,
	NOM         TEXT NOT NULL ,
	PRENOM      TEXT NOT NULL ,
	EMAIL       TEXT NOT NULL ,
	TEL         TEXT NOT NULL ,
	PASSWORD    TEXT NOT NULL ,
	ID_ROLE     TEXT NOT NULL ,
-- 	CONSTRAINT Utilisateur_PK PRIMARY KEY (ID)

	CONSTRAINT Utilisateur_Role_FK FOREIGN KEY (ID_ROLE) REFERENCES Role(ID)
);


CREATE TABLE IF NOT EXISTS Application(
	ID                 TEXT NOT NULL ,
	DATERES            TEXT NOT NULL ,
	DATERESD           TEXT NOT NULL ,
	DATERESRET         TEXT NOT NULL ,
	DATEPR             TEXT ,
	DATERET            TEXT ,
	ID_PASSPORT     TEXT NOT NULL ,
	ID__EXEMPLAIRES    TEXT NOT NULL,
	CONSTRAINT Application_PK PRIMARY KEY (ID)

	,CONSTRAINT Application_Utilisateur_FK FOREIGN KEY (ID_UTILISATEUR) REFERENCES Utilisateur(ID)
	,CONSTRAINT Application_Exemplaires0_FK FOREIGN KEY (ID__EXEMPLAIRES) REFERENCES Exemplaires(ID)
);


CREATE TABLE IF NOT EXISTS Livre_ECRIRE_Auteurs(
	ID          TEXT NOT NULL ,
	ID_LIVRE    TEXT NOT NULL,
	CONSTRAINT ECRIRE_PK PRIMARY KEY (ID,ID_LIVRE)

	,CONSTRAINT ECRIRE_Auteurs_FK FOREIGN KEY (ID) REFERENCES Auteurs(ID)
	,CONSTRAINT ECRIRE_Livre0_FK FOREIGN KEY (ID_LIVRE) REFERENCES Livre(ID)
);


CREATE TABLE IF NOT EXISTS Livre_CONTIENT_Genres(
	ID          TEXT NOT NULL ,
	ID_LIVRE    TEXT NOT NULL,
	CONSTRAINT CONTIENT_PK PRIMARY KEY (ID,ID_LIVRE)

	,CONSTRAINT CONTIENT_Genre_FK FOREIGN KEY (ID) REFERENCES Genre(ID)
	,CONSTRAINT CONTIENT_Livre0_FK FOREIGN KEY (ID_LIVRE) REFERENCES Livre(ID)
);

-- INSERT INTO Role VALUES (0, 'Responsable');
-- INSERT INTO Role VALUES (1, 'Utilisateur');
--
-- INSERT INTO Etat VALUES (1, 'Excellent');
-- INSERT INTO Etat VALUES (2, 'Bon');
-- INSERT INTO Etat VALUES (3, 'Moyen');
-- INSERT INTO Etat VALUES (4, 'Mauvais');


CREATE VIEW IF NOT EXISTS LIVRE_DESCRIPTION AS
    SELECT L.ID AS LivreID, L.IMG, L.TITRE AS LivreTitre, L.DESCRIPTION, L.NB_EX,
           A.ID AS AuthorID, (A.NOM || ' ' || A.PRENOM) AS AUTHOR,
           G.ID AS GenreID, G.TITRE AS GenreTitre
    FROM Livre L INNER JOIN Livre_ECRIRE_Auteurs E ON L.ID = E.ID_LIVRE
        INNER JOIN Auteurs A ON A.ID = E.ID
        INNER JOIN Livre_CONTIENT_Genres C ON C.ID_LIVRE = L.ID
        INNER JOIN Genre G ON C.ID = G.ID


